# Generated by Django 2.1.2 on 2018-10-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
