# Generated by Django 2.1.2 on 2018-10-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_todoitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='user',
            new_name='owner',
        ),
    ]
